### ISSUE TITLE
Pre-launch bugs

### ISSUE THREAD

**Issue by tekd** [GovLab/ogrx-2#16]
Home

- [x] OGRX logo is faint
- [x] Change Submit Research button style to same as browse buttons
- [x] Change "Browse curated lists" to "Selected Readings"
- [x] Labs and Experimentation text is weird
- [x] Submit Research button missing from footer
- [x] All Partners button missing from footer
- [x] Report Errors link in footer doesn't work
- [ ] 

Paper displays 
- [x] Change links to author pages

Authors page

- [x] Letter filter not working
- [x] Authors aren't alphabetized
- [x] Scroll to top button isn't working
- [x] Fix styling of authors on small-medium screens
- [x] Differentiate custom author page links

Custom Author page

- [x] Articles missing
- [x] No Organization badges on cards
- [x] Left justify long bio text (not centered)

Individual Organization page

- [x] description text should be left justified
- [x] No org badges on cards
- [x] Articles missing from Founding Partner pages
- [ ] 

Categories

- [x] Main categories don't go anywhere
- [x] Lost the color coding for main categories

Individual Category pages 

- [x] No org badges on cards

Paper pages
- [x] All Articles/Open Access Articles switch doesn't toggle properly -- papers don't reappear when you switch back to All Articles
- [x] Not displaying download button or any other metadata

Blog

- [x] only displaying markdown

Individual blog posts

- [x] Only displaying markdown

List

- [x] Need a page for all lists, similar to Blog page

Individual list pages

- [x] Title and author in header
- [x] need to display organization (maybe even logo)
- [ ] 

General

- [x] Lots of 404s/path errors
- [x]  Check relative paths (particularly in the top bar)

**Comment by ghost** [comment]
Additional issues:

- [ ]  Ported error submit form, but needs to be hooked up properly and tested

- [x] Hook up sidebar

**Comment by ghost** [comment]
Additional Issues

- [x]  port submission page

**Comment by ghost** [comment]
- [x] clone filters over to other types of results pages

**Comment by chrswng** [comment]
Chris 2nd review issues

- [x] Blog menu item link missing
- [x] Add menu item for Selected Readings
- [x] Change main category to Citizen Engagement (but still point to Citizen Engagement and Crowdsourcing papers, like Behavioral Research)
- [x] Vertical center main category titles
- [x] Digital Engagement org badge looks like wrong blue
- [x] Araz Taeihagh short description left justify https://govlab.github.io/ogrx-2/authors/araz-taeihagh.html
- [x] Citizen engagement and crowdsourcing tag missing color
- [x] Swedish Law and Informatics Research Institute missing articles (i updated the tag to Swedish Law and Informatics Research Institute)
- [x] Change Selected Readings path to /selectedreadings (instead of /lists; i know this will be redundant given the titles of the selected lists, but this way they can give out an easy url like ogrx.org/selectedreadings)
- [x] Change Blog header text to OGRX Blog
- [x] Change Blog Subheader text to News and Insights on Open Governance
- [x] Check Fury Road blog post: on blog page numbered list uses numbers, in post page converted to arrows
- [x] Access this publication button on paper page should be the overlapping style
- [x] Would it be difficult to replace the organization name in the selected readings with their logo? low priority just curious, would look kewl

**Comment by tekd** [comment]
- [ ] fix overlay

**Comment by ghost** [comment]
closing this and adding new issues
